In [2]:
import pandas as pd
import numpy as np
import altair as alt

In [3]:
all_plz_df = pd.read_csv('D:/ft_energy_data_analysis/data/raw/gas/Sep 12 22 17_21_57_gas_15000.csv')

In [4]:
all_plz_df['dataunit'] = all_plz_df['dataunit'].str.replace(',','.').astype(float)
all_plz_df['datafixed'] = all_plz_df['datafixed'].str.replace(',','.').astype(float)

In [5]:
tarife = all_plz_df.drop_duplicates('tariffName')

In [14]:
tarife = tarife[(tarife['tariffName'].str.lower().str.contains('ersatz')) | (tarife['tariffName'].str.lower().str.contains('grund')) | (tarife['tariffName'].str.lower().str.contains('basis')) | (tarife['tariffName'].str.lower().str.contains('classic')) | (tarife['tariffName'].str.lower().str.contains('klassik'))][['providerName', 'tariffName', 'dataunit', 'datafixed']]

In [17]:
tarife.sort_values('tariffName').to_excel('Grundversorger.xlsx', index=False)

In [9]:
all_plz_df.iloc[all_plz_df['dataunit'].argmax()][['rank','plz','location', "pageResultType", "dataeco", "providerName", "tariffName", "datatotal", "costNoBonus", "monthlyPayment", "datafixed", "dataunit", "contractDuration", 
"contractDurationUnit", "cancellationPeriod", "cancellationPeriodUnit", "contractProlongation", "contractProlongationUnit", "priceGuarantee", "priceGuaranteeUnit", "signupPartner"]]

rank                                         31
plz                                       25761
location                    Büsumer Deichhausen
pageResultType                            False
dataeco                                    True
providerName                            stromee
tariffName                          stromee H2O
datatotal                               3492,34
costNoBonus                                3,49
monthlyPayment                           291,03
datafixed                                191.52
dataunit                                 110.03
contractDuration                             12
contractDurationUnit                      month
cancellationPeriod                            4
cancellationPeriodUnit                     week
contractProlongation                          0
contractProlongationUnit                  month
priceGuarantee                               12
priceGuaranteeUnit                        month
signupPartner                                vx
Name: 30, dtype: object

In [13]:
all_plz_df = all_plz_df[[
        'plz',
        'location',
        'providerName', 
          'tariffName',
          'dataunit',
          'datafixed',
          'datatotal',
          'dataeco',
          'signupPartner',
         "contractProlongation",
         "contractProlongationUnit",]].drop_duplicates(subset=['providerName', 'tariffName', 'signupPartner', 'plz']).transform('count')

In [28]:
#all_plz_df[['providerName', 'tariffName', 'signupPartner', 'plz']].groupby(['providerName', 'tariffName', 'signupPartner'])
all_plz_df.groupby(['providerName', 'tariffName', 'signupPartner'])['plz'].agg(list).reset_index()

,providerName,tariffName,signupPartner,plz
0,17er Oberlandenergie,Eintarif,c24,"[63931, 94362, 94362, 94362, 94362, 94362, 943..."
1,BS ENERGY,Grundversorgung Haushalt,c24,"[38100, 38100]"
2,Bergmann,Bergmann Strom,vx,"[38100, 38100]"
3,Bergmann,Bergmann ÖkoStrom,vx,"[38100, 38100]"
4,Berliner Stadtwerke,berlinStrom ÖkoFlex,c24,"[12629, 10245]"
...,...,...,...,...
418,stromee,stromee H2O,c24,"[75382, 71729, 71729, 63931, 94362, 94362, 943..."
419,stromee,stromee H2O,vx,"[75382, 69151, 69151, 69151, 69151, 69151, 973..."
420,swb Bremen,swb Strom basis HH,c24,"[28203, 28207]"
421,swb Bremen,swb Strom proKlima,vx,"[28203, 28207]"
422,vivi-power,vivi-strom,vx,"[75382, 71729, 71729, 63931, 94362, 94362, 943..."

In [16]:
all_plz_df

,plz,location,providerName,tariffName,dataunit,datafixed,datatotal,dataeco,signupPartner,contractProlongation,contractProlongationUnit
0,75382,75382,GMS Gebr. Miller,GMS-Sonderstromvertrag,27.56,99.00,"925,81",1.0,vx,0,month
1,75382,75382,GMS Gebr. Miller,GMS-Sonderstromvertrag mit Schwachlast,27.53,130.00,"956,81",True,vx,0,month
2,75382,75382,EnBW Energie,EnBW Komfort HH,37.31,141.94,"1261,14",False,c24,0,week
3,75382,75382,eins,einsstrom Fix12,41.27,160.53,"1398,61",False,vx,0,month
4,75382,75382,Stadtwerke Walldürn,SWW Aktiv 2022 Eintarifzähler,46.47,89.40,"1483,49",False,c24,1,month
...,...,...,...,...,...,...,...,...,...,...,...
108,82418,Hofheim,stadtenergie,Gönn dir WATT +,60.92,420.49,"2248,09",True,c24,1,month
109,82418,Hofheim,E.ON,E.ON Strom Öko 24,75.87,175.00,"2451,10",True,vx,0,month
110,82418,Hofheim,TEAG,TEAG.Strom extra,83.66,187.09,"2696,89",True,vx,0,month
111,82418,Hofheim,TEAG Thüringer Energie,TEAG.Strom extra,83.66,187.09,"2696,89",True,c24,1,month
112,82418,Hofheim,Brillant Energie,Brillant Strom Natur 24,85.31,178.80,"2738,10",True,vx,0,month

In [8]:
all_plz_df[(((all_plz_df["contractProlongationUnit"]  == 'month') & (all_plz_df["contractProlongation"]  > 1)) | (all_plz_df["contractProlongationUnit"]  == 'year')) ][['providerName', 
                                                        'tariffName', 
                                                        'signupPartner',
                                                        "contractProlongation",
                                                        "contractProlongationUnit"]].drop_duplicates(subset=['providerName', 'tariffName', 'signupPartner']).to_excel('ueber12_monate_verlaengerung.xlsx', sheet_name="nur über anbieter abschlißbare gastarife", index=False)

#.to_excel('ueber12_monate_verlaengerung.xlsx', sheet_name="nur über anbieter abschlißbare gastarife", index=False)

c:\ProgramData\Anaconda3\lib\site-packages\openpyxl\workbook\child.py:99: UserWarning: Title is more than 31 characters. Some applications may not be able to read the file
  warnings.warn("Title is more than 31 characters. Some applications may not be able to read the file")

In [9]:
all_plz_df[(all_plz_df['plz'] == 99425)  & ((all_plz_df['selectedSubmitText'] == 'Tarif nur auf der Webseite des Anbieters abschließbar') | (all_plz_df['selectedSubmitText'] == 'Weiter*')) ][['rank', "pageResultType", "dataeco", "providerName", "tariffName", "datatotal", "costNoBonus", "monthlyPayment", "datafixed", "dataunit", "contractDuration", 
"contractDurationUnit", "cancellationPeriod", "cancellationPeriodUnit", "contractProlongation", "contractProlongationUnit", "priceGuarantee", "priceGuaranteeUnit", "signupPartner"]]

,rank,pageResultType,dataeco,providerName,tariffName,datatotal,costNoBonus,monthlyPayment,datafixed,dataunit,contractDuration,contractDurationUnit,cancellationPeriod,cancellationPeriodUnit,contractProlongation,contractProlongationUnit,priceGuarantee,priceGuaranteeUnit,signupPartner
0,1,0.0,1.0,RheinEnergie,FairBest,"1181,17","1,18","98,43","111,60","35,65",12,month,4,week,0,month,12,month,vx
1,2,False,True,stromee,stromee H2O top12,"1212,04","1,26","105,17","135,71","37,54",12,month,4,week,0,month,12,month,vx
2,3,False,True,eins,einsstrom Online,"1268,92","1,27","105,74","149,73","37,31",12,month,4,week,0,month,12,month,vx
3,4,False,False,eins,einsstrom Fix12,"1331,48","1,33","110,96","158,38","39,10",12,month,4,week,0,month,12,month,vx
4,5,False,True,Knauber Strom,Knauber Strom Sicher 24,"1450,14","1,45","120,85","104,04","44,87",12,month,4,week,0,month,24,month,vx
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37,38,False,False,Stadtwerke Schwerin,meckpommSTROM 12max,"1882,60","2,21","184,57","96,39","70,61",12,month,4,week,0,month,12,month,vx
38,39,False,False,Stadtwerke Flensburg,Flensburg eXtra,"1956,00","1,96","163,00","89,25","62,23",12,month,2,week,0,month,12,month,vx
39,40,False,True,Volkswagen,Volkswagen Naturstrom Blue,"1963,66","1,96","163,64","116,56","61,57",12,month,4,week,0,month,12,month,vx
40,41,False,True,Volkswagen,Volkswagen Naturstrom Connect,"1964,48","1,96","163,71","117,38","61,57",12,month,4,week,0,month,12,month,vx
41,42,False,True,Stadtwerke Flensburg,Flensburg eXtra regio,"1969,06","1,97","164,09","91,59","62,58",12,month,2,week,0,month,12,month,vx

In [14]:
ueber_anbieter_df = all_plz_df[ all_plz_df['selectedSubmitText'] == 'Tarif nur auf der Webseite des Anbieters abschließbar']

In [15]:
ueber_anbieter_df = ueber_anbieter_df.drop_duplicates(subset=['providerName', 'tariffName', 'signupPartner', 'plz'])

In [16]:
plz_list= ueber_anbieter_df.groupby(['providerName', 'tariffName', 'signupPartner'])['plz'].agg(list).reset_index()
plz_list

,providerName,tariffName,signupPartner,plz
0,BS ENERGY,Grundversorgung Haushalt,c24,[38100]
1,Bergmann,Bergmann Strom,vx,[38100]
2,Bergmann,Bergmann ÖkoStrom,vx,[38100]
3,DEW21,Strom Grün,vx,[44147]
4,DEW21,Unser Strom.standard,c24,[44147]
...,...,...,...,...
143,enwag Wetzlar,WetzlarBasisStrom HH,c24,[35578]
144,enwor,onlineStrom fix,vx,"[52080, 52525, 41065]"
145,enwor,onlineStrom fix 2022,c24,"[52080, 52525]"
146,lekker Energie,Grundversorgung Neukunden HH,c24,[52525]
147,swb Bremen,swb Strom basis HH,c24,"[28203, 28207]"

In [17]:
ueber_anbieter_df = ueber_anbieter_df.drop_duplicates(subset=['providerName', 'tariffName', 'signupPartner'])

In [18]:
ueber_anbieter_df[['providerName', 'tariffName', 'signupPartner', 'dataunit', 'datafixed']]

,providerName,tariffName,signupPartner,dataunit,datafixed
0,GMS Gebr. Miller,GMS-Sonderstromvertrag,vx,27.56,99.00
1,GMS Gebr. Miller,GMS-Sonderstromvertrag mit Schwachlast,vx,27.53,130.00
2,EnBW Energie,EnBW Komfort HH,c24,37.31,141.94
3,Stadtwerke Walldürn,SWW Aktiv 2022 Eintarifzähler,c24,46.47,89.40
4,EW Schönau,"EWS Ökostrom inkl. 1,0 Sonnencent",c24,51.20,119.40
...,...,...,...,...,...
0,SWU Stadtwerke Ulm/Neu-Ulm,SWU Strom Grundversorgung,c24,31.54,124.00
1,Energie und Wasser Potsdam,EWP Strom.EchtFlexibel HH,c24,37.96,83.00
0,GEW Wilhelmshaven,havenstrom basis 2022 HH Neukunden,c24,38.47,83.97
0,Harzenergie,Harz Energie basis Strom HH,c24,31.06,99.96
0,WEVG Salzgitter,Salzgitter | Strom flex HH,c24,33.72,129.66

In [19]:
uber_anbieter_plz = pd.merge(
    left=ueber_anbieter_df[['providerName', 'tariffName', 'signupPartner', 'dataunit', 'datafixed']],
    right=plz_list,
    how='inner',
    on=['providerName', 'tariffName', 'signupPartner']
)

In [10]:
uber_anbieter_plz.to_excel('electricity_08_september_nur_anbieter.xlsx', index=False)

In [13]:
ueber_anbieter_df.to_excel('strom_31_juli_nur_anbieter.xlsx', sheet_name="nur über anbieter abschlißbare gastarife", index=False)

In [29]:
anbieter_vormonat = pd.read_excel('D:/ft_energy_data_analysis/notebooks/strom_10_juli_nur_anbieter.xlsx')

In [30]:
anbieter_vormonat = anbieter_vormonat.drop_duplicates(subset=['providerName', 'tariffName', 'signupPartner'])[['providerName', 'tariffName', 'signupPartner']]

In [31]:
vormonat_tarife = anbieter_vormonat.providerName.unique()

neue_tarife = ueber_anbieter_df[~ueber_anbieter_df['tariffName'].isin(vormonat_tarife)]

In [32]:
neue_tarife[ ~neue_tarife['tariffName'].str.lower().str.contains('versorgung') ]

,providerName,tariffName,signupPartner,costNoBonus,costWithBonus,datatotal,dataunit,datafixed,priceGuarantee,priceGuaranteeUnit,contractDuration,contractDurationUnit,contractProlongation,contractProlongationUnit,dataeco,margin,tariffid,plz,recommended,selectedSubmitText
0,EnBW Energie,EnBW Komfort HH,c24,"960,00","960,54","960,54","27,29","141,94",0,month,0,month,0,week,0.0,41,76469.0,75382,1.0,Tarif nur auf der Webseite des Anbieters absch...
1,GMS Gebr. Miller,GMS-Sonderstromvertrag,vx,"1,06","1.058,61","1058,61","31,99","99,00",0,month,0,once,0,month,True,40,849088.0,75382,True,Tarif nur auf der Webseite des Anbieters absch...
2,GMS Gebr. Miller,GMS-Sonderstromvertrag mit Schwachlast,vx,"1,09","1.089,61","1089,61","31,97","130,00",0,month,0,once,0,month,True,40,849089.0,75382,True,Tarif nur auf der Webseite des Anbieters absch...
3,RheinEnergie,FairBest,vx,"1,25","1.246,15","1246,15","37,82","111,60",12,month,12,month,0,month,True,40,872608.0,75382,True,Tarif nur auf der Webseite des Anbieters absch...
4,stromee,stromee H2O top12,vx,"1,33","1.280,60","1280,60","39,76","137,86",12,month,12,month,0,month,True,40,874469.0,75382,True,Tarif nur auf der Webseite des Anbieters absch...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,ZEV,zevstrom Constant 2022,vx,"1,49","1.489,94","1489,94","44,63","151,04",5,month,0,once,0,month,False,40,878557.0,8056,True,Tarif nur auf der Webseite des Anbieters absch...
15,Sw Ludwigslust-Grab.,Lewitzstrom Öko Classic Regional,vx,"1,54","1.510,56","1510,56","45,40","178,56",5,month,0,once,0,month,False,40,866943.0,19053,True,Tarif nur auf der Webseite des Anbieters absch...
23,Sw Ludwigslust-Grab.,Lewitzstrom Öko Plus Regional,vx,"1,57","1.566,66","1566,66","45,99","186,96",5,month,0,once,0,month,True,40,866945.0,19053,True,Tarif nur auf der Webseite des Anbieters absch...
1,SWB Bonn,BeethovenStrom,vx,"1,20","1.203,93","1203,93","36,34","113,76",24,month,12,month,0,month,True,40,874086.0,53111,True,Tarif nur auf der Webseite des Anbieters absch...
4,SWB Bonn,RegionalStrom,vx,"1,32","1.321,50","1321,50","37,91","184,20",24,month,12,month,0,month,True,40,874089.0,53111,True,Tarif nur auf der Webseite des Anbieters absch...

In [25]:
neue_tarife[ ~neue_tarife['tariffName'].str.lower().str.contains('versorgung') ].to_excel('strom_check_august1.xlsx', index=False)

In [45]:
tarifname = 'AuenlandÖKOSTROM'
print(all_plz_df[all_plz_df.tariffName == tarifname].plz.unique())
print(all_plz_df[all_plz_df.tariffName == tarifname].providerName.unique())

[23968 25761 23909]
['Sw Bad Bramstedt' 'Stadtwerke Bramstedt']

In [16]:
all_plz_df.drop_duplicates(['providerName','tariffName', 'plz', 'location'])['dataunit'].str.replace(',','.').astype(float).mean()

26.515420259641132